### ISSUE TITLE
Vorschlag: Ohne externen Vendor arbeiten

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [mizmiz/redaxo-yform_slug#1]
Hi! Bin gerade über den Installer auf dein Addon gestoßen. Kennst du rex_string::normalize()? Das erfüllt den Job ohne zusätzliche slugify-Lib. LG

**Comment by mizmiz** [comment]
Hey Alex, danke für den Tipp. Ich bleibe aber lieber bei einer externen Library. Kyrillische Zeichen werden beispielsweise von  ```rex_string::normalize()``` einfach ersatzlos entfernt.

**Comment by AWqxKAWERbXo** [comment]
Das klingt sinnvoll und notwendig.

**Comment by AWqxKAWERbXo** [comment]
Die Frage allerdings ist, warum du dann nicht auch Leerzeichen und Co. zulassen willst. Auch die sind ja in URLs mittlerweile erlaubt und werden url-encodiert.

**Comment by mizmiz** [comment]
Will ich garnicht. Bei der eingebauten Library wird ```ßüp00   '+ .<>""erwüäöß ereter 12-44xxwyyyw Сьдє лєжитъ``` zu ```ssuep00-erwueaeoess-ereter-12-44xxwyyyw-sde-lezit```
